### ISSUE TITLE
LTA Identity font updated.

### ISSUE THREAD

**Issue by C-Windows-System32-cmd** [jglim/IdentityFont#3]
Managed to update the font that you provided. 

Check the updated font of LTA Identity that I have improved on:
[LTA Identity Font Typeface.zip](https://github.com/jglim/IdentityFont/files/10487719/LTA.Identity.Font.Typeface.zip)

LTA Identity.ttf is the original font you've created.

Identity.ttf is the improved one with characters from Ocean Sans.

**Comment by jglim** [comment]
Hello! 

At this time, I still have not seen symbols in the wild that are used alongside the official LTAIdentity, therefore I am unable to confirm if Ocean Sans is the appropriate fallback typeface.

Your update will still be helpful for folks that might want a reasonable fallback when they encounter missing symbols, and I believe they will appreciate the convenience.

**Comment by C-Windows-System32-cmd** [comment]
Thanks! 
The design is definitely based on Ocean Sans.

This is a rather blurry font of their typeface. Notice the ampersand.
![ter](https://user-images.githubusercontent.com/30820715/216750501-02c8a7e7-2873-40f0-81cf-7869184ca461.png)
